[package]
name = "docksight-attestation"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "docksight_attestation"

[dependencies]
anchor-lang = "0.29.0"

[features]
default = []
